### ISSUE TITLE
"`common`" CPUs should be excluded from CPU page

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/riot-os.org#25]
This issue was raised on the forum during the initial discussion on the original demonstrator.

- https://forum.riot-os.org/t/demo-riot-os-org-website-relaunch/3118/6
- https://forum.riot-os.org/t/demo-riot-os-org-website-relaunch/3118/11

**Comment by leandrolanzieri** [comment]
I think this is now addressed with the way https://github.com/RIOT-OS/riot-os.org/pull/17 generates the data

**Comment by miri64** [comment]
Yepp, checked that with #17 the common CPUs do not show up anymore
