### ISSUE TITLE
External pages should open as `_blank` target

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/riot-os.org#26]
This issue was raised on the forum during the initial discussion on the original demonstrator.

- https://forum.riot-os.org/t/demo-riot-os-org-website-relaunch/3118/7
- https://forum.riot-os.org/t/demo-riot-os-org-website-relaunch/3118/14
- https://forum.riot-os.org/t/demo-riot-os-org-website-relaunch/3118/18
- https://forum.riot-os.org/t/demo-riot-os-org-website-relaunch/3118/22

**Comment by miri64** [comment]
Are there still non `_blank` PRs with #37 merged?

**Comment by jia200x** [comment]
Yes!

**Comment by miri64** [comment]
> Yes!

Why close then?

**Comment by leandrolanzieri** [comment]
😄 I think he meant there are no links without `_blank` left

**Comment by miri64** [comment]
The company links in the user story posts still open in the same tab. E.g. "LOCHA MESH" here https://relaunch.riot-os.org/use_cases/locha.html. But I think for this either the markdown source needs to be adapted or a [dedicated plugin](https://github.com/keithmifsud/jekyll-target-blank) needs to be installed.

**Comment by waehlisch** [comment]
we don't need a separate plugin to enable this.

**Comment by miri64** [comment]
> we don't need a separate plugin to enable this.

Then the markdown needs to be adopted to add the `target="_blank"` attribute to external links within generated content.

**Comment by jia200x** [comment]
> I think he meant there are no links without _blank left

Yes, I meant that. sorry

**Comment by leandrolanzieri** [comment]
> > we don't need a separate plugin to enable this.
> 
> Then the markdown needs to be adopted to add the `target="_blank"` attribute to external links within generated content.

@miri64  this has been fixed in #70
