### ISSUE TITLE
Uses cases: Layout

### ISSUE THREAD

**Issue by waehlisch** [RIOT-OS/riot-os.org#52]
* remove the rounded border of company logos on the Use Case detail page (see https://relaunch.riot-os.org/use_cases/wolfssl.html). Logos should not be modified, except sizes while keeping the ratio of height and width.
* all quote cards (e.g., on the index page) should have the same height. if the quote is too long, it should be shortened automatically by "...".

**Comment by miri64** [comment]
I think it also looks weird that some logos on the main page have more height than others. Maybe make them all the same height rather than the same width?

**Comment by waehlisch** [comment]
@miri64, then it might look weird for others. point is that we cannot change the ratio of width and height. so we have to decide whether we change the height or width. having the same width provides clear columns, see for https://os.mbed.com/. fixing the height could lead to logos that span most of a row.

**Comment by waehlisch** [comment]
@miri64 ,i think what you experience is the difference between good and bad logos. what you propose is already implemented. anyhow.

@leandrolanzieri can you clarify with Lena the best way to show the company logos? please note that we don't want to edit the logos. everything should be handled by a  stylesheet.

**Comment by miri64** [comment]
> @miri64 ,i think what you experience is the difference between good and bad logos. what you propose is already implemented. anyhow.

Ok, let's see how things develop. I raise another flag if that turns out to be not the case :-)

**Comment by leandrolanzieri** [comment]
I contacted Lena regarding this. Her opinion is the following:

>The logo sizes vary a lot and it really makes some partners look more important than others (also it looks a little messy). The reason why it works on the mbed site is, that they don't display the logos in one row, but in several rows. That way you can clearly see that there is a grid and everyone of them actually uses the same space. On the RIOT website the logos are in a single row. There's no recognizable grid and the brain does not understand that the logos are actually the same size.

She proposed then some approaches, and given our current requirements and situation (no manual adjustment of individual logos + not enough logos so far to reach a matrix as mbed), I think the best is to try to add a subtle boundary to the logos to reduce this difference. I'll try to make something like a smooth shadow or light background.
