### ISSUE TITLE
FAQ section still mentions mailling lists

### ISSUE THREAD

**Issue by pokgak** [RIOT-OS/riot-os.org#61]
Under "I have an issue with RIOT code I can't solve. How can I get help?" it still mentions the two mailing lists from before. I think it should be replaced with the forum at least, or removed if not relevant anymore.

**Comment by leandrolanzieri** [comment]
>  It is also a very good idea to search our forum.

The forum is also linked in the answer. Maybe it could be moved to the beginning of the paragraph instead.

**Comment by leandrolanzieri** [comment]
@waehlisch do we keep the mailing lists here?

**Comment by waehlisch** [comment]
yes. hopefully sooner than later we finish the migration, then, the email addresses refer to the Discourse backend.

**Comment by leandrolanzieri** [comment]
Then I guess we can close this.

**Comment by bergzand** [comment]
The migration of the mailing lists addresses to the forum is done. The users@ email address is not used anymore and should be removed from the FAQ entry. See [here](https://forum.riot-os.org/t/start-a-topic-via-email-which-email-addresses/3082/6) for the list of email addresses

**Comment by leandrolanzieri** [comment]
> The migration of the mailing lists addresses to the forum is done. The users@ email address is not used anymore and should be removed from the FAQ entry. See [here](https://forum.riot-os.org/t/start-a-topic-via-email-which-email-addresses/3082/6) for the list of email addresses

Please check https://github.com/RIOT-OS/riot-os.org/pull/83
