### ISSUE TITLE
Add visible link to this repo

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/riot-os.org#79]
Over the launch weekend there were some change suggestions that came in via Twitter, the forum etc. To prevent some indirection via the readers of those sides, how about we add some very visible link to this repo (e.g. something in the direction of [this banner](https://edull24.github.io/fork-me-on-github/) with "Edit me on Github"). This way, people reading the website know immediately that the website can be changed via Git hook and report here or open a PR themselves.

**Comment by waehlisch** [comment]
doesn't look good. we should rather add an FAQ entry.

**Comment by miri64** [comment]
> doesn't look good and gives the wrong impression.

It was just an example, we could find another solution. What wrong impression do you mean?

> we should rather add an FAQ entry.

Question is: will it be seen there by people just browsing through the side and finding errors?

**Comment by waehlisch** [comment]
the focus for the reader should be on the content of the website, not how the content can be changed.

an FAQ entry is helpful. anything that is more prominent is too much. readers who care about the website, we will find the FAQ entry. otherwise, the FAQ is useless anyway.

**Comment by miri64** [comment]
Ok.

**Comment by sirocyl** [comment]
I largely agree. "Fork Me On Github" type banners on the top are in bad taste IMO, and I routinely block them as they get in the way of the page a lot of the time.

However, a link in the footer near the copyright line, "Website source" or something to that effect, wouldn't distract as much, and would be more discoverable than a link in an FAQ.
