### ISSUE TITLE
/api/ redirect broken

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/riot-os.org#80]
duckduckgo still has search results cached at locations like <https://riot-os.org/api/native__cli__eui__provider_8h.html>. I didn't actively check with the old website, but it appears those would earlier redirect to <https://doc.riot-os.org/native__cli__eui__provider_8h.html>, and now they 404.

Can this be fixed here (given we're building a static site), or does this need to be redirected at the server itself?

**Comment by waehlisch** [comment]
i'm wondering whether we should just wait until cache expires. when i seach for `native__cli__eui__provider_8h.html.` i already get a link to https://doc.riot-os.org/native__cli__eui__provider_8h.html as first search result.

**Comment by chrysn** [comment]
Judging from the Python 2 documentation, that time may be measured in
months -- and that's only search results, not bookmarks and incoming
links (hello SEO).

If nginx is used, this is a one-line config item at the ingress point:

```
rewrite ^/api/(.*)$ https://doc.riot-os.org/$1 permanent;
```

**Comment by chrysn** [comment]
It seems that 3 years later, search engines have given up on those paths, and I haven't seen any external links coming in -- and while by now we do have the tools to address this (because the web site is now hosted on tatooine), it has probably become obsolete.
